# Generated by Django 4.2.7 on 2025-10-11 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Логотип компании')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('institution_type', models.CharField(choices=[('university', 'Университет'), ('college', 'Колледж')], default='university', max_length=20, verbose_name='Тип учебного заведения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Университет',
                'verbose_name_plural': 'Университеты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('location', models.CharField(max_length=100, verbose_name='Локация')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('requirements', models.TextField(verbose_name='Требования')),
                ('tech_stack', models.JSONField(default=list, help_text='Список используемых технологий', verbose_name='Стек технологий')),
                ('available_positions', models.PositiveIntegerField(default=1, verbose_name='Количество мест')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='internships.company', verbose_name='Компания')),
                ('universities', models.ManyToManyField(related_name='internships', to='internships.university', verbose_name='Подходящие университеты')),
            ],
            options={
                'verbose_name': 'Практика',
                'verbose_name_plural': 'Практики',
                'ordering': ['-created_at'],
            },
        ),
    ]
