# Generated by Django 4.2.7 on 2025-10-11 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.IntegerField(blank=True, help_text='Номер курса (1-6)', null=True, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internships.university', verbose_name='Университет'),
        ),
    ]
