# Generated by Django 4.2.7 on 2025-10-12 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0005_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='internship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='internships.internship', verbose_name='Практика'),
        ),
    ]
