# Generated by Django 4.2.7 on 2025-10-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0006_alter_application_internship'),
    ]

    operations = [
    ]
