# Generated by Django 4.2.7 on 2025-10-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0006_alter_application_internship'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='student_avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='student',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='student_resumes/', verbose_name='Резюме'),
        ),
    ]
