# Generated by Django 4.2.7 on 2025-10-12 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0008_student_avatar_student_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='avatar',
        ),
    ]
