# Generated by Django 4.2.7 on 2025-10-12 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0009_remove_student_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], help_text='Оценка от 1 до 5 звезд', verbose_name='Рейтинг')),
                ('comment', models.TextField(help_text='Отзыв о прохождении практики', verbose_name='Комментарий')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Анонимный отзыв')),
                ('is_verified', models.BooleanField(default=False, help_text='Отзыв от студента, который действительно проходил практику', verbose_name='Проверенный отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='internships.company', verbose_name='Компания')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='internships.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'company')},
            },
        ),
    ]
