# Generated by Django 4.2.7 on 2025-10-15 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0010_create_review_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, help_text='Email для получения уведомлений о заявках', max_length=254, verbose_name='Email компании'),
        ),
    ]
