# Generated by Django 4.2.7 on 2025-10-15 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0012_make_dates_optional'),
    ]

    operations = [
        # Поле company уже существует в базе данных, но Django не знает об этом
        # Эта миграция отмечает, что поле уже создано
        migrations.AddField(
            model_name='application',
            name='company',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='applications', 
                to='internships.company', 
                verbose_name='Компания'
            ),
        ),
    ]
