# Generated by Django 4.2.7 on 2025-10-17 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internships', '0014_company_is_verified_company_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='verification_status',
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Компания активна в системе', verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Компания прошла модерацию и может публиковать практики', verbose_name='Подтверждена'),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Связанный аккаунт пользователя для входа в систему', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь компании'),
        ),
    ]
