# Generated by Django 4.2.7 on 2025-10-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0015_remove_company_verification_status_company_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='has_blue_checkmark',
            field=models.BooleanField(default=False, help_text='Компания официально подтверждена и использует сервис для ответа на заявки', verbose_name='Синяя галочка'),
        ),
    ]
