# Generated by Django 4.2.7 on 2025-10-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0016_company_has_blue_checkmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='short_description',
            field=models.CharField(blank=True, help_text='Краткое описание компании (до 300 символов)', max_length=300, verbose_name='Краткое описание'),
        ),
    ]
