# Generated by Django 4.2.7 on 2025-10-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0017_company_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='student_avatars/', verbose_name='Аватар студента'),
        ),
    ]
