# Generated by Django 4.2.7 on 2024-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0018_student_avatar'),
    ]

    operations = [
        # Индексы для Company
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_company_name ON internships_company(name);",
            reverse_sql="DROP INDEX IF EXISTS idx_company_name;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_company_is_active ON internships_company(is_active);",
            reverse_sql="DROP INDEX IF EXISTS idx_company_is_active;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_company_is_verified ON internships_company(is_verified);",
            reverse_sql="DROP INDEX IF EXISTS idx_company_is_verified;"
        ),
        
        # Индексы для Internship
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_internship_company ON internships_internship(company_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_internship_company;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_internship_is_active ON internships_internship(is_active);",
            reverse_sql="DROP INDEX IF EXISTS idx_internship_is_active;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_internship_location ON internships_internship(location);",
            reverse_sql="DROP INDEX IF EXISTS idx_internship_location;"
        ),
        
        # Индексы для Student
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_student_user ON internships_student(user_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_student_user;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_student_university ON internships_student(university_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_student_university;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_student_is_active ON internships_student(is_active);",
            reverse_sql="DROP INDEX IF EXISTS idx_student_is_active;"
        ),
        
        # Индексы для Application
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_application_student ON internships_application(student_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_application_student;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_application_internship ON internships_application(internship_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_application_internship;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_application_status ON internships_application(status);",
            reverse_sql="DROP INDEX IF EXISTS idx_application_status;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_application_created_at ON internships_application(created_at);",
            reverse_sql="DROP INDEX IF EXISTS idx_application_created_at;"
        ),
    ]
